version: '3.3'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'developer123'
      POSTGRES_DB: 'shop_and_pay_development'
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000

volumes:
  db_data:
